---
plugin: amazon.aws.aws_ec2 
regions:
  - us-east-1
keyed_groups:
    # group name
  - prefix: arc
    # what you want to find
    key: 'architecture'
  - prefix: tag
    key: 'tags'
  - prefix: aws_region
    key: placement.region
    # creates groups based on tags
  - key: tags.Environment
    separator: ''
  - key: instance_type
    prefix: instance_type