---
- hosts: qa
  tasks:
    - name: Kernel
      debug: msg="{{ ansible_kernel }}"
    - name: Hostname
      debug: msg="{{ ansible_hostname }}"
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - debug: var=ansible_python_version
    # Local variables
    - debug: var=inventory_hostname
    - debug: var=groups
    - debug: var=group_names
    # Same as ansible qa -m setup but for all hosts
    - debug: var=hostvars